### PR TITLE
Raise values from 520 bytes to 1023 bytes and remove "Non-standard name" wording.

### PR DESCRIPTION
**Pull request by thesquatter**
(Removed harassment.)

### CODE REVIEW

**Comment by JeremyRand** [comment]
PR is malware, also harassment is not welcome here.

**Comment by thesquatter** [comment]
How is this malware you dumb bitch and what is harassment?

**Comment by thesquatter** [comment]
Pull request archived and @JeremyRand reported to GitHub for fraud. 
Both the Namecoin Core and Electrum NMC has been fraudulently changed by Jeremy Rand who is openly hostile against the Namecoin project. Let's be assured that I inform WikiPedia admins about this. 

@domob1812 you kick out this scum from the organization or bad things will happen to this repository. 


**Archived version and the full text that has been censored by this scumbag:** 

https://web.archive.org/web/20220523224717/https://github.com/namecoin/electrum-nmc/pull/318


I have raised the maximum value from 520 bytes to 1023 bytes and removed the "Non-standard name" wording.

Namecoin Core does already supporting 1023 bytes for values: namecoin/namecoin-core#512

Regarding the "Non-standard name" I have to say that neither the id/ namespace is standard and some applications may wish to use other namespaces. "Non-standard name" is actually harming Namecoin by trying to force users to use names from the d/ namespace which has been squatted.

id/ namespace is created by @domob1812 who himself squatting well over a thousand "domains" in the d/ namespace. This kind of behavior such as squatting seriously undermines the purpose of Namecoin.

To this end, everyone is free to register names in any namespaces and use in those namespaces to create and use tlds other than .bit.

I have personally seen messages written by @domob1812 offering names from the d/ namespace for thousands of dollars. This is quiet unacceptable considering that he is a squatter.

**Comment by thesquatter** [comment]
You scam artist fraud bitch. You @JeremyRand will get beating up pretty soon! So as your domain squatter fraud buddy @domob1812 both of you will face justice for money laundering too. 

Archived once again: https://archive.ph/OEjQi

**Pull request closed without merging**
