### PR TITLE
Static analysis

### PR DESCRIPTION
**Pull request by robertmin1**
There is some repetition in the Cirrus CI files. Instead of this, we can use if statements and pass arguments directly to the script

### CODE REVIEW

**Comment by JeremyRand** [comment]
Can you split the Bash script update into a separate PR from the Cirrus config update? The Bash script update can go to `master`; the Cirrus config update should go to a stable branch since Cirrus isn't enabled on `master` yet.

**Comment by JeremyRand** [comment]
ACK dbdd5a074cb4069b2b58f168952b5d06dc0afe0b

**Comment by JeremyRand** [comment]
@robertmin1 Can you resubmit this to the `auxpow` branch? No other changes needed.

**Comment by robertmin1** [comment]
Alright! Squashed the commits

**Comment by robertmin1** [comment]
Earlier, you mentioned that the `electrum_nmc/electrum/rsakey.py` file was causing some problems. I've since excluded it.

**Comment by JeremyRand** [comment]
Closing in favor of https://github.com/namecoin/electrum-nmc/pull/376 , let me know if anything is still needed.

**Pull request closed without merging**
