### PR TITLE
UNOList: Add missing check in create_menu

### PR DESCRIPTION
**Pull request by JeremyRand**
Fixes https://github.com/namecoin/electrum-nmc/issues/179

### CODE REVIEW

**Comment by JeremyRand** [comment]
@BugsAllOverMe Mind cherry-picking this commit to see if it fixes the issue you reported?

**Comment by BugsAllOverMe** [comment]
Crash. Now even closing the entire program. 

`/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py:41: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/root/Downloads/Electrum-NMC-3.3.7/electrum_nmc/electrum/gui/qt/uno_list.py", line 289, in configure_selected_item
    show_configure_name(identifier, initial_value, self.parent, False)
  File "Electrum-NMC-3.3.7/electrum_nmc/electrum/gui/qt/configure_name_dialog.py", line 47, in show_configure_name
    d = ConfigureNameDialog(identifier, value, parent, is_new)
  File "Electrum-NMC-3.3.7/electrum_nmc/electrum/gui/qt/configure_name_dialog.py", line 70, in __init__
    formatted_name = format_name_identifier(identifier)
  File "Electrum-NMC-3.3.7/electrum_nmc/electrum/names.py", line 151, in format_name_identifier
    identifier = identifier_bytes.decode("ascii")
AttributeError: 'NoneType' object has no attribute 'decode'
Aborted
`

**Comment by JeremyRand** [comment]
@BugsAllOverMe Is that new traceback happening when you right-click as before, or when you click the `Configure` menu item?

**Comment by BugsAllOverMe** [comment]
@JeremyRand Just close the entire application.

**Comment by JeremyRand** [comment]
Figures, user has vanished.

Anyway, I'd really like to have a regression test for this before we merge the fix.  It's possible that one of the static analyzers will be able to pick up this bug.  I'll investigate that.

**Comment by JeremyRand** [comment]
Merging without a regression test for now; will come back to the regression test later.

**Pull request merged**
