### PR TITLE
Use 100x Bitcoin's fees

### PR DESCRIPTION
**Pull request by JeremyRand**
Fixes https://github.com/namecoin/electrum-nmc/issues/241

### CODE REVIEW

**Comment by JeremyRand** [comment]
I'll merge this if Travis passes (modulo the Regtest job).

**Comment by JeremyRand** [comment]
This breaks the unit tests, so not merging for now.  If needed I'll come back to this PR.

**Comment by JeremyRand** [comment]
@gits7r Can you try cherry-picking https://github.com/namecoin/electrum-nmc/pull/195/commits/baf18aeef1b216235f16b85431bd5fe01563f1cc and check whether it fixes https://github.com/namecoin/electrum-nmc/issues/241 ?

**Comment by JeremyRand** [comment]
> This breaks the unit tests, so not merging for now. If needed I'll come back to this PR.

The unit tests are fixed, so if this is confirmed to fix https://github.com/namecoin/electrum-nmc/issues/241 then we should be able to merge it.

**Comment by JeremyRand** [comment]
I can confirm that it fixes #241 for me; merging shortly.  If there are any remaining issues we can open a new ticket for those.

**Comment by JeremyRand** [comment]
I'll backport this to `master-3.3.10` as well.

**Comment by JeremyRand** [comment]
> I'll backport this to `master-3.3.10` as well.

Backport complete.

**Comment by gits7r** [comment]
yes this fixes it as well. but we already used 100x bitcoin fees, i guess we did not add it at the last upstream refactor. seams ok.

**Pull request merged**
