### PR TITLE
Fix signature creation for segwit/P2SH names

### PR DESCRIPTION
**Pull request by domob1812**
When segwit outputs are spent, BIP143 comes into play to determine how the signature is made.  In particular, the hashed data that is signed for each input also contains the input value.  For name inputs, that should be the locked amount.  Since Electrum sets the value to zero when parsing an output, we have to explicitly set it back to 0.01 NMC for the signature.

This also fixes another compatibility issue between signatures created in Electrum and those expected in Namecoin Core:  The scriptCode part of the hashed input data should not contain the name prefix for "indirected" input types (like P2SH or segwit), while the name prefix is contained for ordinary P2PK and P2PKH inputs.

### CODE REVIEW

**Comment by domob1812** [comment]
Tested with `pytest`, and also verified `name_update`'s on regtest with legacy (P2PKH), segwit, multisig-legacy (P2SH) and multisig-segwit wallets.

**Comment by JeremyRand** [comment]
ACK d0e7a5d5dfb3d0a0bf561200a5e0af40d68e4335. I have not tested the code, but I have reviewed it and it looks OK, I agree it can be merged, subject to a Travis check.

**Comment by domob1812** [comment]
Thanks for the review!  Out of curiosity, what exactly does Travis check?  More than running `pytest` locally?  It seems to me that lots of code is actually untested, and I wonder if there are some tests that I just haven't seen yet.

**Comment by JeremyRand** [comment]
Triggering a Travis rebuild...

**Comment by JeremyRand** [comment]
> Out of curiosity, what exactly does Travis check?

@domob1812 Off the top of my head, it verifies that binaries can be built for all major platforms without errors, and it also runs a Namecoin-specific static analysis script that looks for likely rebranding errors.  There might be other things too (I seem to recall that upstream Electrum is considering adding some static analysis stuff to Travis, not sure if they merged that yet).

**Comment by JeremyRand** [comment]
The only Travis fail here is for the Windows target, and the error looks unrelated to this PR.

**Pull request merged**
