### PR TITLE
Not Data, it's Value

### PR DESCRIPTION
**Pull request by namecoin-core-admin**
Fix

### CODE REVIEW

**Comment by JeremyRand** [comment]
The harassment is not appreciated, but the linter fix is.  Factored out the linter fix to https://github.com/namecoin/electrum-nmc/pull/321 .

**Comment by namecoin-core-admin** [comment]
Nope. I'm not Zoltan.

Pull request I sent has been closed, not merged, including censored. 

You merged my commit in your name. This Namecoin project with you @JeremyRand is a disgrace, You are the only reason why this project is unsuccessful. Those people on Telegram @Namecoin channel are correct about you. 

You should look for other projects instead of harassing, censoring, attacking, naming and accusing contributors that they want to merge "malware".

**Comment by namecoin-core-admin** [comment]
**JeremyRand:is-none** branch. Oh the irony. :rofl:  https://github.com/namecoin/electrum-nmc/pull/321

**Comment by namecoin-core-admin** [comment]
Everything is archived Mr. https://archive.ph/fwHhQ
Keep censoring with the namecoin user and this project will say bye bye to you.

**Comment by namecoin-core-admin** [comment]
I'm for free speech except when you talk about me
censor me Mr Wanna-be-cool-working-on-Namecoin-Rand

**Comment by namecoin-core-admin** [comment]
WikiLeaks.bit is squatted by a mental fucked idiot called @JeremyRand who pretends that he is for free speech, except when someone criticize him, then he will delete comments in an Anti-Censorship projects name, in this case Namecoin. 

Congrats, you can't be more retarded than this.

**Comment by JeremyRand** [comment]
I don't think we have any interest in the other wording changes in this PR, so closing.  If someone else (who's not evading bans) wants to open an issue to discuss wording changes, feel free.

**Comment by namecoin-core-admin** [comment]
Stop talking in other people's name. You all the time use "We" when in reality you are totally alone.

**Comment by namecoin-core-admin** [comment]
Screenshot 2022-05-24 at 03-04-46 Fix None linter fails by JeremyRand · Pull Request #321 · namecoin_electrum-nmc

**Comment by namecoin-core-admin** [comment]
Looking good @JeremyRand you make Namecoin great again.

**Pull request closed without merging**
