### PR TITLE
Warn user if they try to register a name whose registration is already in-progress

### PR DESCRIPTION
**Pull request by JeremyRand**
Fixes https://github.com/namecoin/electrum-nmc/issues/236

### CODE REVIEW

**Comment by JeremyRand** [comment]
This PR depends on https://github.com/namecoin/electrum-nmc/pull/245 .

**Comment by JeremyRand** [comment]
#245 is merged, so is no longer blocking this PR.  This PR still needs to be tested.

**Comment by JeremyRand** [comment]
Tested and working.  It still fails to detect the case where the `name_firstupdate` has been broadcasted but has 0 confirmations, but I think we can address that in a future PR.

**Comment by JeremyRand** [comment]
@gits7r Do we need to backport this one?  I suspect that backporting it will be messy; might be best to save this one for the 4.0.0 release.

**Comment by gits7r** [comment]
ACK, agree to keep this one for 4.0.0, messy backports eat a lot of coding time which we need to apply all our proper changes to 0.4.0 branch and patch all the refactorings from upstream. But it's a must, from UX perspective and usability.

**Pull request merged**
