### PR TITLE
Support parsing DNS records from binary values (CBOR)

### PR DESCRIPTION
**Pull request by robertmin1**
Resulting DNS records get passed to DNS Builder GUI

### CODE REVIEW

**Comment by robertmin1** [comment]
We can also try. parsing Json first

**Comment by JeremyRand** [comment]
Code review looks OK, testing now...

**Comment by JeremyRand** [comment]
ACK cf135bab7d289e1d22d6d38a61149adb013db223

**Comment by robertmin1** [comment]
I'm not certain where we should add the `cbor` dependency (Requirements)

**Comment by JeremyRand** [comment]
Not sure, but I'll probably deal with it when I'm next tagging a release.

**Pull request merged**
